# Generated by Django 5.2.3 on 2025-07-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level1', models.IntegerField(choices=[(1, 'Basics'), (2, 'Technik'), (3, 'Taktik'), (4, 'Weitere')], default=1)),
                ('level2', models.IntegerField(choices=[(1, 'Offense'), (2, 'Defense'), (3, 'Transition'), (4, 'Fitness'), (5, 'Weitere')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Drill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('intensity', models.IntegerField(choices=[(1, 'Leicht'), (2, 'Mittel'), (3, 'Intensiv'), (4, 'Sehr intensiv'), (5, 'Extrem intensiv')], default=1)),
                ('difficulty', models.IntegerField(choices=[(1, 'Einfach'), (2, 'Mittel'), (3, 'Schwierig'), (4, 'Sehr schwierig'), (5, 'Extrem schwierig')], default=1)),
                ('skills', models.ManyToManyField(related_name='drills', to='coaching_app.skill')),
            ],
        ),
    ]
