# Generated by Django 5.2.3 on 2025-07-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drill',
            name='stats',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
