# Generated by Django 5.2.3 on 2025-10-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_app', '0002_drill_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.DurationField()),
                ('actions', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('drills', models.ManyToManyField(related_name='trainings', to='coaching_app.drill')),
            ],
        ),
    ]
