# Generated by Django 5.2.3 on 2025-12-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_app', '0003_training'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='time',
            new_name='duration',
        ),
        migrations.AddField(
            model_name='training',
            name='player_count',
            field=models.IntegerField(default=10),
        ),
    ]
