# Generated by Django 5.2.3 on 2026-01-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_app', '0004_rename_time_training_duration_training_player_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='notes',
            new_name='description',
        ),
        migrations.AddField(
            model_name='training',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
