# Generated by Django 5.2.3 on 2026-01-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_app', '0005_rename_notes_training_description_training_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='stats',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
