# Generated by Django 5.2.3 on 2026-01-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_app', '0006_training_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
