# Generated by Django 5.2.3 on 2026-01-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_app', '0007_training_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drill',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'sehr einfach'), (2, 'eher einfach'), (3, 'schwierig'), (4, 'sehr schwierig'), (5, 'extrem schwierig')], default=1),
        ),
        migrations.AlterField(
            model_name='drill',
            name='intensity',
            field=models.IntegerField(choices=[(1, 'nicht intensiv'), (2, 'weniger intensiv'), (3, 'intensiv'), (4, 'sehr intensiv'), (5, 'extrem intensiv')], default=1),
        ),
    ]
