# Generated by Django 5.2.3 on 2026-02-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_app', '0008_alter_drill_difficulty_alter_drill_intensity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='drill',
            name='equipment',
            field=models.ManyToManyField(related_name='drills', to='coaching_app.equipment'),
        ),
    ]
