# Generated by Django 5.2.3 on 2026-02-08 09:33

import coaching_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_app', '0009_equipment_drill_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='drill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=coaching_app.models.drill_image_path),
        ),
        migrations.AddField(
            model_name='drill',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
