# Generated by Django 5.2.3 on 2026-02-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_app', '0010_drill_image_drill_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='equipment',
            field=models.ManyToManyField(related_name='trainings', to='coaching_app.equipment'),
        ),
    ]
