# Generated by Django 5.2.3 on 2026-02-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_app', '0011_training_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='drill',
            name='level1',
            field=models.IntegerField(blank=True, choices=[(1, 'Basics'), (2, 'Technik'), (3, 'Taktik'), (4, 'Weitere')], null=True),
        ),
        migrations.AddField(
            model_name='drill',
            name='level2',
            field=models.IntegerField(blank=True, choices=[(1, 'Offense'), (2, 'Defense'), (3, 'Transition'), (4, 'Fitness'), (5, 'Weitere')], null=True),
        ),
    ]
