# Generated by Django 5.2.3 on 2026-02-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_app', '0012_drill_level1_drill_level2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drill',
            name='equipment',
            field=models.ManyToManyField(blank=True, null=True, related_name='drills', to='coaching_app.equipment'),
        ),
    ]
